### PR TITLE
TVHeadend: Filter channels, add DVR section and enable scrolling for secondary text.

### PR DESCRIPTION
**Pull request by gb160**
TVHeadend: Initially filter channels into channel tag sections rather than 1 long list of channels, and add DVR section if completed recordings are present. (homebrew/TVHeadend/homebrew.js)

Add function and css to detect and apply scrolling to secondary text if it exceeds the size of container, prevents secondary text from spilling onto >1 line which can overlay onto main text. Ideally would be done just with css but don't think its possible. (assets/carouselView.js, assets/main.css)

### CODE REVIEW

**Comment by john-tornblom** [comment]
Thank you, I will have a closer look at this when I got some spare time.
One question, is the scrolling text

**Comment by gb160** [comment]
Hi John
Yes the text only scrolls when it is overflowing 1 line. Short text is not affected, so is aligned centrally,  as it was previously.

**Comment by john-tornblom** [comment]
I've had a look, and the updates to homebrew/TVHeadend/homebrew.js looks neat!

I only have a couple of comments:
- Don't make changes that goes beyond the description of the PR (like changing the secondaryText for the TVHeadend entry. If you don't like the current text, send a separate PR for that).
- Don't include useless changes like the new value for BASE_URL, or added spaces like on line 34. Make those changes in a separate PR if you think they should be changed.

Regarding the scrolling text, it would be much nicer if the scrolling would go back and forth, i.e., scroll to the left until there is no overflow to the right, then change the animation to scroll to the right until there is no overflow to the left. Do you think you can be pull that off?

I suggest that you send a second PR for only the changes in homebrew/TVHeadend/homebrew.js (after fixing my minor comments), then we can try to investigate improvements to the scrolling, sounds OK?

**Comment by gb160** [comment]
No problem John, I will close this PR and create 2 new PRs taking your comments into consideration.

**Pull request closed without merging**
